### ISSUE TITLE
Exclude directory option required

### ISSUE THREAD

**Issue by dziamid** [Crimx/postcss-safe-important#2]
I need to apply `!important` to the styles that originated from src/ while keeping any imported styles from node_modules/ intact. Is it possible to add such an option to the plugin? Is this easier to approach by having 2 different webpack loaders for src/ and module_modules/ styles?

**Comment by crimx** [comment]
Hi, I think it's possible. I'll take a look and see what I can do.

**Comment by crimx** [comment]
This should do the trick now(suppose you postcss config file is at project root):

```javascript
postcss([ safeImportant({
    paths: p => p.startsWith(path.resolve(__dirname, './node_modules'))
}) ]);
```

**Comment by dziamid** [comment]
Awesome, already using it, thanks!

**Comment by crimx** [comment]
Glad it works. :) Closing it now.
