### ISSUE TITLE
Full Example of usage

### ISSUE THREAD

**Issue by vdtest555** [Crimx/postcss-safe-important#5]
I would like a full example where I give the plugin  a .css file path and outputs a string.

I do not understand what is happening in the example.

It should be inside a file.js that I will run from the command line with 'node file.js'.

**Comment by crimx** [comment]
This is a PostCSS plugin. Just follow the PostCSS [docs](https://github.com/postcss/postcss).

**Comment by crimx** [comment]
Updated [examples](https://github.com/crimx/postcss-safe-important?tab=readme-ov-file#example).
