### ISSUE TITLE
Possible to exclude !important on CSS custom variables

### ISSUE THREAD

**Issue by grelas** [Crimx/postcss-safe-important#6]
I have CSS custom variables that get modified via javascript, but the `!important` takes precedence. Is it possible to exclude CSS vars?

**Comment by crimx** [comment]
Hi. Could you provide some examples?

**Comment by grelas** [comment]
Sure! 

I have a class with a local CSS custom variable.
```
.foo {
   --bar: 400px;
   width: var(--bar);
   background-color: white;
}
```

The output using postcss-safe-important looks like:
```
.foo {
   --bar: 400px !important;
   width: var(--bar) !important;
   background-color: white !important;
}
```

I have a React component which tries to set the `--bar` variable, but the `!important` takes precedence:
```
const { width } = props;
const style = {
      '--bar': width
}
<div style={style} className="foo" />
```

Does that make sense?

**Comment by grelas** [comment]
@crimx I'm happy to submit a PR to include this, but wondering if you think this should be default behavior or if its better to add a boolean option like `excludeCSSVars` to the plugin. Excluding CSS custom variables would be useful if the loader is transforming CSS from node_modules (e.g. using a third-party library) - in which you cannot add `/* no important */` to certain rules.

**Comment by crimx** [comment]
`postcss-safe-important@2.0.1` now supports CSS Variables.

The code is a bit old so I just refactored the entire project and also updated the API.

**Comment by crimx** [comment]
Declaration exclusion also works with CSS Variables btw.

**Comment by grelas** [comment]
Awesome thanks @crimx !
