### ISSUE TITLE
What breaking changes were there in 2.0.0?

### ISSUE THREAD

**Issue by saxoncameron** [Crimx/postcss-safe-important#8]
I'd like to upgrade but I can't find a changelog, migration notes, or a GitHub release either here or on NPM. Could you please advise what the breaking change was so I can check if I need to make any change after bumping the version?

**Comment by crimx** [comment]
Hi sorry I forgot to add the changelog. Most of the APIs are changed in 2.0. The 1.0 APIs are still supported, no breaking changes included.

**Comment by saxoncameron** [comment]
Awesome, thanks for confirming 👌

**Comment by crimx** [comment]
As for migration I think the API readme should be self-explanatory. Let me know if you have any trouble migrating.
